apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mad-roadshow
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/feven-redhat/mad-roadshow.git
status: {}
